import { cookies } from "next/headers";
import DashboardLayout from "./components/layout/DashboardLayout";
import "./globals.css";
import Login from "./components/login/page";

export const metadata = {
  title: "Dashboard",
  description: "Generated by Shimanto",
};

export default async function RootLayout({ children }) {
  const cookie = await cookies();
  const myCookie = cookie.get("token")?.value;

  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="/icon?<generated>"
          type="image/<generated>"
          sizes="<generated>"
        />
      </head>
      <body className="flex mt-20">
        {myCookie ? (
          <Login />
        ) : (
          <>
            <DashboardLayout />

            <div className="md:ml-57 w-full pr-6">{children}</div>
          </>
        )}
      </body>
    </html>
  );
}
