export const productData = [
  {
    id: 1,
    name: "Cubitt Smart Watch",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    price: "$576.28",
    sku: "FROX-13563",
    status: "Active",
    qty: 556,
    rating: 5,
    sales: "186 / 2058",
    image: "/images/watch1.png",
  },
  {
    id: 2,
    name: "Cubitt Smart Watch",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    price: "$576.28",
    sku: "FROX-13563",
    status: "Active",
    qty: 556,
    rating: 5,
    sales: "186 / 2058",
    image: "/images/headphone1.png",
  },
  {
    id: 3,
    name: "Cubitt Smart Watch",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    price: "$576.28",
    sku: "FROX-13563",
    status: "Active",
    qty: 556,
    rating: 5,
    sales: "186 / 2058",
    image: "/images/headphone2.png",
  },
  {
    id: 4,
    name: "Cubitt Smart Watch",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    price: "$576.28",
    sku: "FROX-13563",
    status: "Active",
    qty: 556,
    rating: 5,
    sales: "186 / 2058",
    image: "/images/watch2.png",
  },
];