export const CustomersData = [
  {
    id: 1,
    name: "Raymond Barton",
    email: "tim.jennings@site.com",
    phone: "+099 856 245",
    addressLine1: "1126 S San Jose Dr",
    addressLine2: "Abilene, Texas(TX), 79605",
    status: "Online",
    joined: "28 Jan 2022",
    avatar: "/images/user1.png",
  },
  {
    id: 2,
    name: "Gary Simmons",
    email: "josephw@me.com",
    phone: "+099 856 245",
    addressLine1: "198 Maciver St",
    addressLine2: "Bishop, California(CA), 93514",
    status: "Online",
    joined: "28 Jan 2022",
    avatar: "/images/user2.png",
  },
  {
    id: 3,
    name: "Doug Bird",
    email: "josephw@me.com",
    phone: "+099 856 245",
    addressLine1: "718 Boyce St",
    addressLine2: "Madisonville, Kentucky(KY)",
    status: "Offline",
    joined: "28 Jan 2022",
    avatar: "/images/user3.png",
  },
  {
    id: 4,
    name: "Georgia Burgess",
    email: "tubajon@me.com",
    phone: "+099 856 245",
    addressLine1: "7 N Main St",
    addressLine2: "Lowell, North Carolina(NC)",
    status: "Online",
    joined: "28 Jan 2022",
    avatar: "/images/user4.png",
  },
  {
    id: 5,
    name: "Ray Smart",
    email: "retoh@mac.com",
    phone: "+099 856 245",
    addressLine1: "24575 Highway W",
    addressLine2: "Waynesville, Missouri(MO)",
    status: "Online",
    joined: "28 Jan 2022",
    avatar: "/images/user5.png",
  },
  {
    id: 6,
    name: "Calvin Robinson",
    email: "itstatus@sbcglobal.net",
    phone: "+099 856 245",
    addressLine1: "9255 N Magnolia Ave #SPC 271",
    addressLine2: "Santee, California(CA)",
    status: "Online",
    joined: "28 Jan 2022",
    avatar: "/images/user6.png",
  },
  {
    id: 7,
    name: "Andrea Elliott",
    email: "dexter@live.com",
    phone: "+099 856 245",
    addressLine1: "2 Court St",
    addressLine2: "Binghamton, New York(NY)",
    status: "Online",
    joined: "28 Jan 2022",
    avatar: "/images/user1.png",
  },
  {
    id: 8,
    name: "Phoebe Abbott",
    email: "citizenl@att.net",
    phone: "+099 856 245",
    addressLine1: "Abbottstown, Pennsylvania(PA)",
    addressLine2: "17301",
    status: "Offline",
    joined: "28 Jan 2022",
    avatar: "/images/user2.png",
  },
  {
    id: 9,
    name: "Laurel Estrada",
    email: "noahb@msn.com",
    phone: "+099 856 245",
    addressLine1: "13728 Utica Ave",
    addressLine2: "Robbins, Illinois(IL), 60472",
    status: "Online",
    joined: "28 Jan 2022",
    avatar: "/images/user3.png",
  },
  {
    id: 10,
    name: "Percy Hawkins",
    email: "dmbkiwi@aol.com",
    phone: "+099 856 245",
    addressLine1: "2718 2036th Hwy",
    addressLine2: "Whitesburg, Kentucky(KY)",
    status: "Online",
    joined: "28 Jan 2022",
    avatar: "/images/user4.png",
  },
  {
    id: 11,
    name: "Gabrielle",
    email: "chaffar@gmail.com",
    phone: "+099 856 245",
    addressLine1: "2906 Pine Lake Rd",
    addressLine2: "Uniontown",
    status: "Offline",
    joined: "28 Jan 2022",
    avatar: "/images/user5.png",
  },
  {
    id: 12,
    name: "Justin",
    email: "wildfire@live.com",
    phone: "+099 856 245",
    addressLine1: "7722 Coachman Ln",
    addressLine2: "Jenison, Michigan(MI)",
    status: "Online",
    joined: "28 Jan 2022",
    avatar: "/images/user6.png",
  },
];
